#!/bin/bash
# Description: Display cover for the current playing song using notify-send

# get current album
album=$(ncmpcpp --current-song={%b} 2> /dev/null)

# If album not null display cover
if [[ -n "$album" ]];then
        if [[ "$album" = "Nasheed" ]];then
                image="/home/mohabaks/Pictures/notify/nasheed/cover.png"
                notify-send -i $image "Now Playing " "$(mpc current)"
        elif [[ "$album" = "Quran — Shatri" ]];then
                image="/home/mohabaks/Pictures/notify/quran/cover.png"
                notify-send -i $image "Now Playing" "$(mpc current)"
        fi
else
        image="/home/mohabaks/Pictures/notify/other/cover.png"
        notify-send -i $image "Now Playing" "$(mpc current)"
fi
