#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config single_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a singing_wind state=floating

# compton --config $HOME/.config/compton/compton.conf &
xsetroot -cursor_name left_ptr
$HOME/.config/polybar/launch.sh
xdo above -t $(xdo id -n root) $(xdo id -n polybar)
feh --bg-tile $HOME/.config/bspwm/greyfloral.png
